# Generated by Django 2.1.7 on 2019-03-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id', models.AutoField(help_text='ID Tip de Transaccion', primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(help_text='Descripcion', max_length=50)),
                ('Estado', models.BooleanField(default=1)),
            ],
        ),
    ]
