# Generated by Django 2.1.7 on 2019-03-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipotransaccion',
            old_name='Estado',
            new_name='Activo',
        ),
        migrations.AddField(
            model_name='tipotransaccion',
            name='Tipo',
            field=models.CharField(choices=[('I', 'Ingresos'), ('E', 'Egresos'), ('R', 'Renglones de Egresos'), ('P', 'Tipos de Pagos')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='tipotransaccion',
            name='id',
            field=models.AutoField(help_text='ID Tipo de Transaccion', primary_key=True, serialize=False),
        ),
    ]
