# Generated by Django 2.1.7 on 2019-03-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='limite',
            field=models.IntegerField(default=0),
        ),
    ]
