# Generated by Django 2.1.7 on 2019-03-09 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_auto_20190308_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.AutoField(help_text='ID Usuario', primary_key=True, serialize=False)),
                ('Ano', models.IntegerField(default=2019, help_text='Ano', validators=[django.core.validators.MinValueValidator(2000)])),
                ('Mes', models.CharField(choices=[('Ene', 'Enero'), ('Feb', 'Febrero'), ('Mar', 'Marzo'), ('Abr', 'Abril'), ('May', 'Mayo'), ('Jun', 'Junio'), ('Jul', 'Julio'), ('Ago', 'Agosto'), ('Sep', 'Septiembre'), ('Oct', 'Octubre'), ('Nov', 'Noviembre'), ('Dic', 'Diciembre')], default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GestionEgresos',
            fields=[
                ('id', models.AutoField(help_text='ID Gestion de Egreso', primary_key=True, serialize=False)),
                ('TipoEgreso', models.CharField(help_text='Tipo de egreso', max_length=50)),
                ('RenglonEgreso', models.CharField(help_text='Renglon de egreso', max_length=50)),
                ('TipoPagoxDefecto', models.CharField(help_text='Forma De Pago', max_length=50)),
                ('Descripcion', models.CharField(help_text='Descripcion', max_length=50)),
                ('EstadoActivo', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GestionIngresos',
            fields=[
                ('id', models.AutoField(help_text='ID Gestion de Ingreso', primary_key=True, serialize=False)),
                ('TipoIngreso', models.CharField(help_text='Tipo de ingreso', max_length=50)),
                ('Origen', models.CharField(help_text='Institucion/Cliente/Empleador', max_length=50)),
                ('Descripcion', models.CharField(help_text='Descripcion', max_length=50)),
                ('EstadoActivo', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GestionUsuarios',
            fields=[
                ('id', models.AutoField(help_text='ID Usuario', primary_key=True, serialize=False)),
                ('Nombre', models.CharField(help_text='Nombre de Usuario', max_length=50)),
                ('Cedula', models.CharField(help_text='Cedula', max_length=50)),
                ('Limite', models.CharField(help_text='Limite de Egresos del Periodo', max_length=50)),
                ('TipoPersona', models.CharField(choices=[('F', 'Fisica'), ('J', 'Juridica')], default='', max_length=1)),
                ('EstadoActivo', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.AutoField(help_text='ID Usuario', primary_key=True, serialize=False)),
                ('TipoTransaccion', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso')], default='', max_length=1)),
                ('TipoPago', models.CharField(choices=[('TC', 'Tarjeta de Credito'), ('E', 'Efectivo'), ('C', 'Cheque')], default='', max_length=1)),
                ('FechaRegistro', models.DateField(auto_now=True)),
                ('Monto', models.CharField(help_text='Monto Transaccion', max_length=12)),
                ('Descripcion', models.CharField(help_text='Descripcion', max_length=50)),
                ('EstadoActivo', models.BooleanField(default=1)),
                ('Usuario', models.ForeignKey(on_delete=None, to='finanzas.GestionUsuarios')),
            ],
        ),
    ]
