# Generated by Django 2.1.7 on 2019-03-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_auto_20190316_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuente',
            old_name='Nombre',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='tipopago',
            old_name='Nombre',
            new_name='Descripcion',
        ),
    ]
