# Generated by Django 2.1.7 on 2019-03-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_corte_gestionegresos_gestioningresos_gestionusuarios_transacciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='Usuario',
            field=models.ForeignKey(default='', on_delete=None, to='finanzas.GestionUsuarios'),
        ),
        migrations.AlterField(
            model_name='corte',
            name='id',
            field=models.AutoField(help_text='ID Corte', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='id',
            field=models.AutoField(help_text='ID Transaccion', primary_key=True, serialize=False),
        ),
    ]
