# Generated by Django 2.1.7 on 2019-04-02 15:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_auto_20190316_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionesCorte',
            fields=[
                ('id', models.AutoField(help_text='ID Transaccion', primary_key=True, serialize=False)),
                ('EstadoActivo', models.BooleanField(default=1)),
                ('fecha', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='transacciones',
            name='FechaTransaccion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='transaccionescorte',
            name='Transaccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='finanzas.Transacciones'),
        ),
        migrations.AddField(
            model_name='transaccionescorte',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaccionescorte',
            name='corte',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='finanzas.Corte'),
        ),
    ]
