# Generated by Django 2.1.7 on 2019-03-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_auto_20190309_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='Mes',
            field=models.CharField(choices=[('Ene', 'Enero'), ('Feb', 'Febrero'), ('Mar', 'Marzo'), ('Abr', 'Abril'), ('May', 'Mayo'), ('Jun', 'Junio'), ('Jul', 'Julio'), ('Ago', 'Agosto'), ('Sep', 'Septiembre'), ('Oct', 'Octubre'), ('Nov', 'Noviembre'), ('Dic', 'Diciembre')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='TipoPago',
            field=models.CharField(choices=[('T', 'Tarjeta de Credito'), ('E', 'Efectivo'), ('C', 'Cheque')], default='', max_length=1),
        ),
    ]
