# Generated by Django 2.1.7 on 2019-04-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_auto_20190402_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccionescorte',
            old_name='EstadoActivo',
            new_name='estado',
        ),
    ]
