# Generated by Django 2.1.7 on 2019-03-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_auto_20190309_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='BalanceCorte',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corte',
            name='BalanceInicial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corte',
            name='FechaCorte',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='corte',
            name='TotalEgresos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corte',
            name='TotalIngresos',
            field=models.IntegerField(default=0),
        ),
    ]
