# Generated by Django 2.1.7 on 2019-04-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_auto_20190402_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccionescorte',
            old_name='estado',
            new_name='Activo',
        ),
    ]
